//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDataQueryService")]
public interface IDataQueryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPoiStatesWithBuffer", ReplyAction="http://tempuri.org/IDataQueryService/GetPoiStatesWithBufferResponse")]
    string GetPoiStatesWithBuffer(string idField, string stateField, string xField, string yField, string updateFields, string tableName, double x, double y, double distance);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/Search", ReplyAction="http://tempuri.org/IDataQueryService/SearchResponse")]
    string Search(string keywords, string searchField, string otherFields, string tableName, int searchCount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBuilding", ReplyAction="http://tempuri.org/IDataQueryService/GetBuildingResponse")]
    string GetBuilding(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBuildingByBid", ReplyAction="http://tempuri.org/IDataQueryService/GetBuildingByBidResponse")]
    string GetBuildingByBid(string bid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPremisesByKeywords", ReplyAction="http://tempuri.org/IDataQueryService/GetPremisesByKeywordsResponse")]
    string GetPremisesByKeywords(string keywords, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPremisesByBid", ReplyAction="http://tempuri.org/IDataQueryService/GetPremisesByBidResponse")]
    string GetPremisesByBid(string bid, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetIntersectingRoads", ReplyAction="http://tempuri.org/IDataQueryService/GetIntersectingRoadsResponse")]
    string GetIntersectingRoads(string roadName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetRoadShape", ReplyAction="http://tempuri.org/IDataQueryService/GetRoadShapeResponse")]
    string GetRoadShape(string roadName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetCrossingShape", ReplyAction="http://tempuri.org/IDataQueryService/GetCrossingShapeResponse")]
    string GetCrossingShape(string roadName1, string roadName2);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetAllOneWayTraffic", ReplyAction="http://tempuri.org/IDataQueryService/GetAllOneWayTrafficResponse")]
    string GetAllOneWayTraffic();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetAllLiveTraffic", ReplyAction="http://tempuri.org/IDataQueryService/GetAllLiveTrafficResponse")]
    string GetAllLiveTraffic();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetLiveTrafficByRoadRank", ReplyAction="http://tempuri.org/IDataQueryService/GetLiveTrafficByRoadRankResponse")]
    string GetLiveTrafficByRoadRank(string roadRank);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetLiveTraffic", ReplyAction="http://tempuri.org/IDataQueryService/GetLiveTrafficResponse")]
    string GetLiveTraffic(string roadRank, int speedRank);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetLiveTrafficSpeedRankByRoadRank", ReplyAction="http://tempuri.org/IDataQueryService/GetLiveTrafficSpeedRankByRoadRankResponse")]
    string GetLiveTrafficSpeedRankByRoadRank(string roadRank);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetLiveTrafficSpeedRank", ReplyAction="http://tempuri.org/IDataQueryService/GetLiveTrafficSpeedRankResponse")]
    string GetLiveTrafficSpeedRank(string roadRank, int speedRank);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetFirstTenWestLakeScenes", ReplyAction="http://tempuri.org/IDataQueryService/GetFirstTenWestLakeScenesResponse")]
    string GetFirstTenWestLakeScenes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetSecondTenWestLakeScenes", ReplyAction="http://tempuri.org/IDataQueryService/GetSecondTenWestLakeScenesResponse")]
    string GetSecondTenWestLakeScenes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThirdTenWestLakeScenes", ReplyAction="http://tempuri.org/IDataQueryService/GetThirdTenWestLakeScenesResponse")]
    string GetThirdTenWestLakeScenes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetSecurityHousing", ReplyAction="http://tempuri.org/IDataQueryService/GetSecurityHousingResponse")]
    string GetSecurityHousing();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeTypes", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeTypesResponse")]
    string GetThemeTypes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetStreet", ReplyAction="http://tempuri.org/IDataQueryService/GetStreetResponse")]
    string GetStreet(string districtid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetCommunity", ReplyAction="http://tempuri.org/IDataQueryService/GetCommunityResponse")]
    string GetCommunity(string communityname, string streetid, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeDataByCode", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeDataByCodeResponse")]
    string GetThemeDataByCode(string name, string typeid, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeDataByTypeIDs", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeDataByTypeIDsResponse")]
    string GetThemeDataByTypeIDs(string name, string typeid, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeDataLineByTypeIDs", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeDataLineByTypeIDsResponse")]
    string GetThemeDataLineByTypeIDs(string name, string typeid, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeDataFromTable", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeDataFromTableResponse")]
    string GetThemeDataFromTable(string code);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeAttriData", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeAttriDataResponse")]
    string GetThemeAttriData(string code, string identifier, string fields);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetHotPoi", ReplyAction="http://tempuri.org/IDataQueryService/GetHotPoiResponse")]
    string GetHotPoi();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetHotPoiImage", ReplyAction="http://tempuri.org/IDataQueryService/GetHotPoiImageResponse")]
    string GetHotPoiImage();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetLabelUser", ReplyAction="http://tempuri.org/IDataQueryService/GetLabelUserResponse")]
    string GetLabelUser(string userid, string name, int start, int end, bool isQueryCount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBookMark", ReplyAction="http://tempuri.org/IDataQueryService/GetBookMarkResponse")]
    string GetBookMark(string userid, string name, int start, int end, bool isQueryCount);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBookMarkByKey", ReplyAction="http://tempuri.org/IDataQueryService/GetBookMarkByKeyResponse")]
    string GetBookMarkByKey(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetEnterpriseRegisterPoint", ReplyAction="http://tempuri.org/IDataQueryService/GetEnterpriseRegisterPointResponse")]
    string GetEnterpriseRegisterPoint(double x, double y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetImageList", ReplyAction="http://tempuri.org/IDataQueryService/GetImageListResponse")]
    string GetImageList(string foreignID, string tableName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetMistakeList", ReplyAction="http://tempuri.org/IDataQueryService/GetMistakeListResponse")]
    string GetMistakeList(string identifier);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBasicInfo", ReplyAction="http://tempuri.org/IDataQueryService/GetBasicInfoResponse")]
    string GetBasicInfo(string name, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetRoads", ReplyAction="http://tempuri.org/IDataQueryService/GetRoadsResponse")]
    string GetRoads();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetStreetShape", ReplyAction="http://tempuri.org/IDataQueryService/GetStreetShapeResponse")]
    string GetStreetShape(string streetID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetCommunityShape", ReplyAction="http://tempuri.org/IDataQueryService/GetCommunityShapeResponse")]
    string GetCommunityShape(string communityID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBufferPoi", ReplyAction="http://tempuri.org/IDataQueryService/GetBufferPoiResponse")]
    string GetBufferPoi(string typeid, double x, double y, double distance, int start, int end);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetBufferFlssTypePoiCount", ReplyAction="http://tempuri.org/IDataQueryService/GetBufferFlssTypePoiCountResponse")]
    string GetBufferFlssTypePoiCount(string typeids, double x, double y, double distance);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeInfo", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeInfoResponse")]
    string GetThemeInfo(string themeName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeLastUpdateTime", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeLastUpdateTimeResponse")]
    string GetThemeLastUpdateTime(string themeName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetThemeStates", ReplyAction="http://tempuri.org/IDataQueryService/GetThemeStatesResponse")]
    string GetThemeStates(string themeID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPois", ReplyAction="http://tempuri.org/IDataQueryService/GetPoisResponse")]
    string GetPois(string idField, string xField, string yField, string otherFields, string tableName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPoisWithBuffer", ReplyAction="http://tempuri.org/IDataQueryService/GetPoisWithBufferResponse")]
    string GetPoisWithBuffer(string idField, string xField, string yField, string otherFields, string tableName, double x, double y, double distance);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataQueryService/GetPoiStates", ReplyAction="http://tempuri.org/IDataQueryService/GetPoiStatesResponse")]
    string GetPoiStates(string idField, string stateField, string updateFields, string tableName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDataQueryServiceChannel : IDataQueryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataQueryServiceClient : System.ServiceModel.ClientBase<IDataQueryService>, IDataQueryService
{
    
    public DataQueryServiceClient()
    {
    }
    
    public DataQueryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataQueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataQueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataQueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetPoiStatesWithBuffer(string idField, string stateField, string xField, string yField, string updateFields, string tableName, double x, double y, double distance)
    {
        return base.Channel.GetPoiStatesWithBuffer(idField, stateField, xField, yField, updateFields, tableName, x, y, distance);
    }
    
    public string Search(string keywords, string searchField, string otherFields, string tableName, int searchCount)
    {
        return base.Channel.Search(keywords, searchField, otherFields, tableName, searchCount);
    }
    
    public string GetBuilding(double x, double y)
    {
        return base.Channel.GetBuilding(x, y);
    }
    
    public string GetBuildingByBid(string bid)
    {
        return base.Channel.GetBuildingByBid(bid);
    }
    
    public string GetPremisesByKeywords(string keywords, int start, int end)
    {
        return base.Channel.GetPremisesByKeywords(keywords, start, end);
    }
    
    public string GetPremisesByBid(string bid, int start, int end)
    {
        return base.Channel.GetPremisesByBid(bid, start, end);
    }
    
    public string GetIntersectingRoads(string roadName)
    {
        return base.Channel.GetIntersectingRoads(roadName);
    }
    
    public string GetRoadShape(string roadName)
    {
        return base.Channel.GetRoadShape(roadName);
    }
    
    public string GetCrossingShape(string roadName1, string roadName2)
    {
        return base.Channel.GetCrossingShape(roadName1, roadName2);
    }
    
    public string GetAllOneWayTraffic()
    {
        return base.Channel.GetAllOneWayTraffic();
    }
    
    public string GetAllLiveTraffic()
    {
        return base.Channel.GetAllLiveTraffic();
    }
    
    public string GetLiveTrafficByRoadRank(string roadRank)
    {
        return base.Channel.GetLiveTrafficByRoadRank(roadRank);
    }
    
    public string GetLiveTraffic(string roadRank, int speedRank)
    {
        return base.Channel.GetLiveTraffic(roadRank, speedRank);
    }
    
    public string GetLiveTrafficSpeedRankByRoadRank(string roadRank)
    {
        return base.Channel.GetLiveTrafficSpeedRankByRoadRank(roadRank);
    }
    
    public string GetLiveTrafficSpeedRank(string roadRank, int speedRank)
    {
        return base.Channel.GetLiveTrafficSpeedRank(roadRank, speedRank);
    }
    
    public string GetFirstTenWestLakeScenes()
    {
        return base.Channel.GetFirstTenWestLakeScenes();
    }
    
    public string GetSecondTenWestLakeScenes()
    {
        return base.Channel.GetSecondTenWestLakeScenes();
    }
    
    public string GetThirdTenWestLakeScenes()
    {
        return base.Channel.GetThirdTenWestLakeScenes();
    }
    
    public string GetSecurityHousing()
    {
        return base.Channel.GetSecurityHousing();
    }
    
    public string GetThemeTypes()
    {
        return base.Channel.GetThemeTypes();
    }
    
    public string GetStreet(string districtid)
    {
        return base.Channel.GetStreet(districtid);
    }
    
    public string GetCommunity(string communityname, string streetid, int start, int end)
    {
        return base.Channel.GetCommunity(communityname, streetid, start, end);
    }
    
    public string GetThemeDataByCode(string name, string typeid, int start, int end)
    {
        return base.Channel.GetThemeDataByCode(name, typeid, start, end);
    }
    
    public string GetThemeDataByTypeIDs(string name, string typeid, int start, int end)
    {
        return base.Channel.GetThemeDataByTypeIDs(name, typeid, start, end);
    }
    
    public string GetThemeDataLineByTypeIDs(string name, string typeid, int start, int end)
    {
        return base.Channel.GetThemeDataLineByTypeIDs(name, typeid, start, end);
    }
    
    public string GetThemeDataFromTable(string code)
    {
        return base.Channel.GetThemeDataFromTable(code);
    }
    
    public string GetThemeAttriData(string code, string identifier, string fields)
    {
        return base.Channel.GetThemeAttriData(code, identifier, fields);
    }
    
    public string GetHotPoi()
    {
        return base.Channel.GetHotPoi();
    }
    
    public string GetHotPoiImage()
    {
        return base.Channel.GetHotPoiImage();
    }
    
    public string GetLabelUser(string userid, string name, int start, int end, bool isQueryCount)
    {
        return base.Channel.GetLabelUser(userid, name, start, end, isQueryCount);
    }
    
    public string GetBookMark(string userid, string name, int start, int end, bool isQueryCount)
    {
        return base.Channel.GetBookMark(userid, name, start, end, isQueryCount);
    }
    
    public string GetBookMarkByKey(string id)
    {
        return base.Channel.GetBookMarkByKey(id);
    }
    
    public string GetEnterpriseRegisterPoint(double x, double y)
    {
        return base.Channel.GetEnterpriseRegisterPoint(x, y);
    }
    
    public string GetImageList(string foreignID, string tableName)
    {
        return base.Channel.GetImageList(foreignID, tableName);
    }
    
    public string GetMistakeList(string identifier)
    {
        return base.Channel.GetMistakeList(identifier);
    }
    
    public string GetBasicInfo(string name, int start, int end)
    {
        return base.Channel.GetBasicInfo(name, start, end);
    }
    
    public string GetRoads()
    {
        return base.Channel.GetRoads();
    }
    
    public string GetStreetShape(string streetID)
    {
        return base.Channel.GetStreetShape(streetID);
    }
    
    public string GetCommunityShape(string communityID)
    {
        return base.Channel.GetCommunityShape(communityID);
    }
    
    public string GetBufferPoi(string typeid, double x, double y, double distance, int start, int end)
    {
        return base.Channel.GetBufferPoi(typeid, x, y, distance, start, end);
    }
    
    public string GetBufferFlssTypePoiCount(string typeids, double x, double y, double distance)
    {
        return base.Channel.GetBufferFlssTypePoiCount(typeids, x, y, distance);
    }
    
    public string GetThemeInfo(string themeName)
    {
        return base.Channel.GetThemeInfo(themeName);
    }
    
    public string GetThemeLastUpdateTime(string themeName)
    {
        return base.Channel.GetThemeLastUpdateTime(themeName);
    }
    
    public string GetThemeStates(string themeID)
    {
        return base.Channel.GetThemeStates(themeID);
    }
    
    public string GetPois(string idField, string xField, string yField, string otherFields, string tableName)
    {
        return base.Channel.GetPois(idField, xField, yField, otherFields, tableName);
    }
    
    public string GetPoisWithBuffer(string idField, string xField, string yField, string otherFields, string tableName, double x, double y, double distance)
    {
        return base.Channel.GetPoisWithBuffer(idField, xField, yField, otherFields, tableName, x, y, distance);
    }
    
    public string GetPoiStates(string idField, string stateField, string updateFields, string tableName)
    {
        return base.Channel.GetPoiStates(idField, stateField, updateFields, tableName);
    }
}
